"""Bellwether subscriber risk chart.

Edit the CONFIG block below, then run:
    python3 docs/make_chart.py

No LLM, no Snowflake. Reads docs/chart_data.json (regenerated by the
pipeline; static copy included below as fallback if the file is missing).
"""

import json
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG — edit everything here
# ─────────────────────────────────────────────────────────────────────────────

# Output
OUT_FILE    = Path(__file__).parent / "subscriber_risk_by_archetype.png"
DPI         = 160          # increase for print (300), decrease for quick preview (72)
OPEN_AFTER  = True         # open in Preview after saving (macOS)

# Figure size in inches (width, height)
FIG_SIZE = (15, 7.2)

# Spacing between the two panels (0 = touching, 0.5 = half a panel width apart)
PANEL_GAP = 0.40

# Title & subtitle
TITLE         = "Bellwether  ·  26,584 Active Thesis Subscribers Scored"
TITLE_SIZE    = 14
TITLE_Y       = 0.97       # 0 = bottom of figure, 1 = top

SUBTITLE_SIZE = 9.5
SUBTITLE_Y    = 0.935

# Panel titles
PANEL1_TITLE = "Subscribers by Archetype & Risk Tier"
PANEL2_TITLE = "Revenue at Risk by Archetype"
PANEL_TITLE_SIZE = 11

# Axis labels
PANEL1_YLABEL = "Active Thesis subscribers"
PANEL2_XLABEL = "Expected revenue at risk  ($79 x P(churn))"
AXIS_LABEL_SIZE = 10

# Bar width (0–1; wider = bars touch)
BAR_WIDTH = 0.55

# Risk tier colours
COLOR_LOW    = "#3A3A6A"   # low risk  (P < 0.10)  — dark so it recedes
COLOR_MEDIUM = "#F5A623"   # medium risk (0.10 ≤ P < 0.50)
COLOR_HIGH   = "#C95F5F"   # high risk  (P ≥ 0.50)

# Archetype colours (right panel bars)
ARCH_COLORS = {
    "price":       "#4F86C6",
    "efficacy":    "#E07B54",
    "fatigue":     "#6DBF82",
    "life_change": "#A97DC9",
    "stimulant":   "#E8C540",
    "involuntary": "#C95F5F",
}

# Labels shown on the chart axes (edit for line breaks, abbreviations, etc.)
ARCH_LABELS = {
    "price":       "Price",
    "efficacy":    "Efficacy",
    "fatigue":     "Overstock /\nFatigue",
    "life_change": "Life Change",
    "stimulant":   "Stimulant",
    "involuntary": "Involuntary\n(Payment)",
}

# Order of archetypes on the charts (left to right / bottom to top)
ARCH_ORDER = ["life_change", "involuntary", "efficacy", "fatigue", "price"]

# Background / panel colours
COLOR_BG    = "#0F0F1E"
COLOR_PANEL = "#16162A"
COLOR_GRID  = "#222238"
COLOR_WHITE = "#FFFFFF"
COLOR_MUTED = "#8888AA"

# Font sizes
TICK_LABEL_SIZE  = 9
LEGEND_SIZE      = 8
VALUE_LABEL_SIZE = 8.5

# ─────────────────────────────────────────────────────────────────────────────
# DATA — loaded from chart_data.json; fallback inline if file missing
# ─────────────────────────────────────────────────────────────────────────────

FALLBACK_DATA = {
    "summary": {
        "price":       {"total": 17300, "low": 16440, "medium": 766, "high": 94,  "revenue_at_risk": 25960},
        "efficacy":    {"total":   870, "low":   680, "medium": 190, "high":  0,  "revenue_at_risk":  4071},
        "fatigue":     {"total":  1009, "low":   953, "medium":  56, "high":  0,  "revenue_at_risk":  1576},
        "life_change": {"total":  6728, "low":  6090, "medium": 638, "high":  0,  "revenue_at_risk": 14300},
        "stimulant":   {"total":    11, "low":    11, "medium":   0, "high":  0,  "revenue_at_risk":     0},
        "involuntary": {"total":   666, "low":   163, "medium": 503, "high":  0,  "revenue_at_risk": 13464},
    },
    "totals": {
        "active_subscribers": 26584,
        "at_risk_medium_high": 2247,
        "revenue_at_risk": 59370,
        "sub_value_assumption": 79.0,
    }
}

data_path = Path(__file__).parent / "chart_data.json"
if data_path.exists():
    with open(data_path) as f:
        data = json.load(f)
else:
    print("chart_data.json not found — using built-in fallback data", file=sys.stderr)
    data = FALLBACK_DATA

summary = data["summary"]
totals  = data["totals"]

subtitle = (
    f"Total revenue at risk: ${totals['revenue_at_risk']:,.0f}"
    f"   |   {totals['at_risk_medium_high']:,} at medium-to-high risk"
    f"   |   Monthly value at ${totals['sub_value_assumption']:.0f}/cycle"
)

# ─────────────────────────────────────────────────────────────────────────────
# CHART
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=FIG_SIZE, facecolor=COLOR_BG)
fig.subplots_adjust(wspace=PANEL_GAP, top=0.88, bottom=0.12)

x = np.arange(len(ARCH_ORDER))

# ── Panel 1: stacked bar by risk tier ─────────────────────────────────────
ax = axes[0]
ax.set_facecolor(COLOR_PANEL)
for sp in ax.spines.values():
    sp.set_edgecolor(COLOR_GRID)
ax.tick_params(colors=COLOR_MUTED, labelsize=TICK_LABEL_SIZE)
ax.yaxis.grid(True, color=COLOR_GRID, lw=0.6, ls="--", alpha=0.6)
ax.set_axisbelow(True)

low_vals = np.array([summary[a]["low"]    for a in ARCH_ORDER], dtype=float)
med_vals = np.array([summary[a]["medium"] for a in ARCH_ORDER], dtype=float)
hi_vals  = np.array([summary[a]["high"]   for a in ARCH_ORDER], dtype=float)

ax.bar(x, low_vals,                         BAR_WIDTH, color=COLOR_LOW,    label="Low risk  (P < 0.10)")
ax.bar(x, med_vals, BAR_WIDTH, bottom=low_vals,                color=COLOR_MEDIUM, label="Medium risk  (0.10 to P < 0.50)", alpha=0.88)
ax.bar(x, hi_vals,  BAR_WIDTH, bottom=low_vals + med_vals,     color=COLOR_HIGH,   label="High risk  (P >= 0.50)", alpha=0.92)

for i, arch in enumerate(ARCH_ORDER):
    total = summary[arch]["total"]
    top   = low_vals[i] + med_vals[i] + hi_vals[i]
    if total > 0:
        ax.text(x[i], top + 100, f"{total:,}", ha="center", va="bottom",
                fontsize=VALUE_LABEL_SIZE, color=COLOR_WHITE, fontweight="bold")

ax.set_xticks(x)
ax.set_xticklabels([ARCH_LABELS[a] for a in ARCH_ORDER], color=COLOR_MUTED, fontsize=TICK_LABEL_SIZE)
ax.set_ylabel(PANEL1_YLABEL, color=COLOR_MUTED, fontsize=AXIS_LABEL_SIZE, labelpad=8)
ax.set_title(PANEL1_TITLE, color=COLOR_WHITE, fontsize=PANEL_TITLE_SIZE, fontweight="bold", pad=10)
ax.legend(fontsize=LEGEND_SIZE, framealpha=0.2, facecolor=COLOR_PANEL,
          edgecolor=COLOR_GRID, labelcolor=COLOR_WHITE, loc="upper right")

# ── Panel 2: horizontal revenue bars ──────────────────────────────────────
ax2 = axes[1]
ax2.set_facecolor(COLOR_PANEL)
for sp in ax2.spines.values():
    sp.set_edgecolor(COLOR_GRID)
ax2.tick_params(colors=COLOR_MUTED, labelsize=TICK_LABEL_SIZE)
ax2.xaxis.grid(True, color=COLOR_GRID, lw=0.6, ls="--", alpha=0.6)
ax2.set_axisbelow(True)

rev_vals   = np.array([summary[a]["revenue_at_risk"] for a in ARCH_ORDER], dtype=float)
bar_colors = [ARCH_COLORS[a] for a in ARCH_ORDER]
ax2.barh(x, rev_vals, BAR_WIDTH, color=bar_colors, alpha=0.88, edgecolor=COLOR_BG, linewidth=0.5)

max_rev = rev_vals.max()
for i, val in enumerate(rev_vals):
    if val > 200:
        ax2.text(val + max_rev * 0.01, x[i], f"${val:,.0f}", va="center",
                 fontsize=VALUE_LABEL_SIZE, color=COLOR_WHITE, fontweight="bold")

ax2.set_yticks(x)
ax2.set_yticklabels([ARCH_LABELS[a] for a in ARCH_ORDER], color=COLOR_MUTED, fontsize=TICK_LABEL_SIZE)
ax2.set_xlabel(PANEL2_XLABEL, color=COLOR_MUTED, fontsize=AXIS_LABEL_SIZE, labelpad=8)
ax2.set_title(PANEL2_TITLE, color=COLOR_WHITE, fontsize=PANEL_TITLE_SIZE, fontweight="bold", pad=10)

# ── Banner ─────────────────────────────────────────────────────────────────
fig.text(0.5, TITLE_Y,    TITLE,    ha="center", va="top", fontsize=TITLE_SIZE,    fontweight="bold", color=COLOR_WHITE)
fig.text(0.5, SUBTITLE_Y, subtitle, ha="center", va="top", fontsize=SUBTITLE_SIZE, color=COLOR_MUTED)

# ─────────────────────────────────────────────────────────────────────────────
# SAVE
# ─────────────────────────────────────────────────────────────────────────────

plt.savefig(OUT_FILE, dpi=DPI, bbox_inches="tight", facecolor=COLOR_BG)
print(f"Saved: {OUT_FILE}")

if OPEN_AFTER:
    import subprocess
    subprocess.run(["open", str(OUT_FILE)])
